### ISSUE TITLE
Cannot run due to relative import

### ISSUE THREAD

**Issue by mick-d** [victorlei/smop#122]
```
Traceback (most recent call last):
  File "<conda_env>/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "<conda_env>/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "<bin_dir>/smop-master/smop/main.py", line 15, in <module>
    from . import options
ValueError: Attempted relative import in non-package

```

**Comment by victorlei** [comment]
Fixed in 0.40

**Comment by azimb** [comment]
Just cloned the repo from master and I'm still facing the same issue. Simply ran `python main.py solver.m` and I get the following error:

![image](https://user-images.githubusercontent.com/38919150/75003682-a9aee500-5436-11ea-90c6-9e7eff3b5dbb.png)

**Comment by geraman21** [comment]
@azimb Hi ! Did you manage ti fix this issue ? Facing the same problem rn...

**Comment by Uio96** [comment]
Me too. The problem seems to exist in the latest version.

**Comment by Ananyapam7** [comment]
Me too.
